# Builds a single-file embed: dist/nirnex-chatbot.js
# Combines knowledge-base.js + nirnex-chatbot.js and inlines nirnex-chatbot.css
# into the CSS placeholder so the widget is a one-script-tag embed.

$ErrorActionPreference = "Stop"

$dir = Split-Path -Parent $MyInvocation.MyCommand.Path
$css = Get-Content -Raw -Encoding UTF8 (Join-Path $dir "nirnex-chatbot.css")
$kb  = Get-Content -Raw -Encoding UTF8 (Join-Path $dir "knowledge-base.js")
$js  = Get-Content -Raw -Encoding UTF8 (Join-Path $dir "nirnex-chatbot.js")

# Escape CSS as a JS double-quoted string (escape backslashes, quotes, newlines)
$cssEscaped = $css -replace [regex]::Escape('\'), '\\' -replace [regex]::Escape('"'), '\"' -replace "`r`n", '\n' -replace "`n", '\n'
$jsBuilt = $js.Replace("/*__CSS__*/", $cssEscaped)

$outs = @()
$outs += "/* =========================================================`n   NirnexAI AI Assistant - single-file embed`n   Generated by build.ps1 - do not edit directly.`n   Usage: <script src=""dist/nirnex-chatbot.js""></script>`n   Set window.NirnexChatbotConfig before loading to customize.`n   ========================================================= */`n"
$outs += $kb
$outs += $jsBuilt
$out = ($outs -join "`n")

$dist = Join-Path $dir "dist"
if (-not (Test-Path $dist)) { New-Item -ItemType Directory -Path $dist | Out-Null }

[System.IO.File]::WriteAllText((Join-Path $dist "nirnex-chatbot.js"), $out, (New-Object System.Text.UTF8Encoding($false)))
Write-Host ("Built: " + (Join-Path $dist 'nirnex-chatbot.js') + " (" + (Get-Item (Join-Path $dist 'nirnex-chatbot.js')).Length + " bytes)")